[package]
name = "iobluetooth-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swift-bridge = "0.1.41"
lazy_static = "1.4.0"

[build-dependencies]
swift-bridge-build = "0.1.41"
